### ISSUE TITLE
Development build is incomplete

### ISSUE THREAD

**Issue by PyvesB** [fappel/xiliary#101]
Hello @fappel !

The "Eclipse SWT Auxiliaries" bundle is not present on the development P2 repository:
<img width="664" alt="Screenshot 2020-07-17 at 11 01 48" src="https://user-images.githubusercontent.com/10694593/87770170-f26c9d80-c81e-11ea-8245-9dcb60d7a4e2.png">

However, things seem fine on the main one:
<img width="668" alt="Screenshot 2020-07-17 at 11 02 03" src="https://user-images.githubusercontent.com/10694593/87770210-01535000-c81f-11ea-83cd-90af51caf2ba.png">

Did something go wrong with the latest build script run?

Thanks in advance!

Pyves

**Comment by fappel** [comment]
Well, the Eclipse SWT Auxiliaries never was listed in the category.xml. I wonder how this ever could work. Added the missing entry and hope that it is available after the build has finished. Otherwise, there must be another reason...

**Comment by PyvesB** [comment]
I think it's now present, thanks! I'll do some more digging around and report back if I find anything of interest.

<img width="581" alt="Screenshot 2020-07-17 at 12 15 48" src="https://user-images.githubusercontent.com/10694593/87775989-4aa79d80-c827-11ea-8925-9d8f578c9d22.png">

You're right, it's surprising how it ever could work. Maybe some newer version of plugin tools got pulled in from one of the update sites, and that now works differently with regards to features and categorisation?

**Comment by fappel** [comment]
I had the same thought, but I'm glad that it works now. Thanks for reporting the bug
