### ISSUE TITLE
Unable to connect to repository

### ISSUE THREAD

**Issue by yedan2010** [fappel/xiliary#106]
Unable to connect to repository http://fappel.github.io/xiliary/content.xml
Unable to connect to repository http://fappel.github.io/xiliary/content.xml
Connect to fappel.github.io:80 [fappel.github.io/127.0.0.1] failed: Connection refused: connect
![image](https://user-images.githubusercontent.com/375227/98892178-bf8b9b00-24da-11eb-8e99-1e6be5298db7.png)

**Comment by fappel** [comment]
Thanks for reporting this. I will have a look at it ASAP.

**Comment by fappel** [comment]
I just tried an installation via Eclipse and it worked like a charm. However, the location you've used looked wrong to me because there is no content.xml at the specified location. This is because the xiliary p2 repository is a composite repository.
