### ISSUE TITLE
Adding a selection listener to FlatScrollBar via addListener() doesn't work

### ISSUE THREAD

**Issue by fipro78** [fappel/xiliary#15]
I tried to use the FlatScrollBar with a NatTable. Since NatTable internally keeps track of the scrollbars itself and provides API to exchange the scrollbar via IScroller interface, I created a NatTable wrapper for the FlatScrollBar. 

It renders correctly, but scrolling doesn't work. As far as I can see, the issue is that in NatTable the listeners for selection are added via addListener(SWT.Selection, Listener) were FlatScrollBar only supports SelectionListener.

It would be great if FlatScrollBar would also support Listeners for the SWT.Selection event, since I think also some SWT widgets work that way.

**Comment by fappel** [comment]
Sounds like a valid use case. If you could provide a code snippet of what  you are doing, this would be most helpful to reproduce the behavior and verify a possible fix efficiently.

**Comment by fipro78** [comment]
Are you familiar with NatTable? Because a simple snippet won't help you on
reproducing the issue. I attach the whole example part I created for this.

You can get the model and the service class via
https://gist.github.com/fipro78/d67a58baa8f56024648a

The NatTable Getting Started Tutorial was published a few days ago at
vogella: http://www.vogella.com/tutorials/NatTable/article.html

But regarding the internals of NatTable regarding handling of scrolling,
well that would take a while.

Looking for example at the Slider implementation, addSelectionListener() is
wrapping the SelectionListener in a TypedListener and registers it via
addListener(SWT.Selection, typedListener). I suppose you need something
similar.

Something like changing the Collection<SelectionListener> to
Collection<Listener>, implement the addSelectionListener like in Slider and
override addListener so for eventType SWT.Selection the listener gets added
to the local list. But that is just an idea, I'm not sure about the
implementation details of FlatScrollBar. But for me it looks like an Event
and therefore Listener should be sufficient since you are not setting and
using further information in the created SelectionEvent.

**Comment by fappel** [comment]
Solved with 6f480d1f43acb06f6c38c2c95c27945677e22ceb
