### ISSUE TITLE
Make FlatScrollBar stylable

### ISSUE THREAD

**Issue by fipro78** [fappel/xiliary#16]
Currently it is not possible to style the FlatScrollBar. It would be at least nice to set the background color (increment region) and the color of the thumb.

**Comment by fappel** [comment]
That's true. Styling is of course a missing feature. I was thinking about a style object containing the possible capabilities of the bar. But I haven't made up my mind completely yet..

**Comment by fipro78** [comment]
As a quick solution you could add two setters for the background color of the increment region and the color of the thumb. As these the only two stylable components on the first look, it would help in attaching the FlatScrollBar to a dark themed table for example.
Via such setters it would also be possible to add CSS styling capabilities.
An enhancement for a style object could still be added when you have made up your mind. :)

**Comment by jbuchberger** [comment]
Great stuff! Is it possible to add styling for increment button length as well?
Maybe like this:
> `flat-scroll-bar-button-length: 7;`

**Comment by fappel** [comment]
Yes, I think this should be possible. I've opened the enhancement issue #46 for discussion and progress tracking on that topic.
