### ISSUE TITLE
The sonar project association dialog is unresponsive with this theme

### ISSUE THREAD

**Issue by gayanper** [fappel/xiliary#31]
The sonar project association dialog is unresponsive with this theme. The project association table is not editable and the scrollbar doesn't move either. But nothing can be found on the eclipse error log about this. Probably the UI initialization is failing which cause the whole table to be unresponsive for input events.

**Comment by fappel** [comment]
Thanks for reporting this issue. Might be related to #30.

**Comment by fappel** [comment]
Commit  87ebe9a seems to fix the problem successfully. A quick smoke test confirmed that the table is editable again with the changes in place. However, feel free to reopen this issue if the problem persists.

**Comment by gayanper** [comment]
Tested and Its Fixed

**Comment by fappel** [comment]
Great! Thank you very much :-)
