### ISSUE TITLE
[ScrollableAdapter]  when using EGit the dialog that displays after a push has no visible content in the top half where the tree view was

### ISSUE THREAD

**Issue by fappel** [fappel/xiliary#33]

**Comment by paulbilnoski** [comment]
Here is a screen shot of the Push Confirmation dialog, which has the issue.

![push dialog](https://cloud.githubusercontent.com/assets/2455397/10951567/d5534c4a-8303-11e5-9139-22a97743d391.png)

**Comment by paulbilnoski** [comment]
I discovered that I could resize the dialog to get the content to display, making the issue minor rather than more critical. It then appears to be a simple "missing refresh" issue.
