### ISSUE TITLE
[ScrollableAdapter]  blank content on Git Synchronize Wizard

### ISSUE THREAD

**Issue by fappel** [fappel/xiliary#43]
Some further information on the Git Synchronize window: It shows blank content for me when I simply click "next" on the first page ("select from available synchronization types") when "Git" is already selected. If I double-click the "Git" entry in the list to advance the page, the content shows properly. This does not occur when using the "SVN" synchronization type.

This issue has been swapped from issue https://github.com/fappel/xiliary/issues/38#issuecomment-155873697, reported by [paulbilnoski](https://github.com/paulbilnoski).

**Comment by fappel** [comment]
I can reproduce the problem, but I have to select 'next' by key combination, meaning hitting of 'alt + n'. Weird, indeed.

**Comment by fappel** [comment]
Strange at is is, it looks like it is also necessary to have the mouse hovering above the dialog while pressing ALT+N to make the problem appear. This seems to block the redrawing of the table somehow.

**Comment by fappel** [comment]
Fixed the problem with blank content on Git Synchronize Wizard - at least I cannot reproduce it anymore in my workspace ;-) Pretty tricky adjustment in ItemHeightMeasurementEnabler. Although all tests are green I hope there is no regression else where. This is because the integration coverage feels a bit thin due to the complex usage scenarios of all the possible extensions. So, I keep fingers crossed...

**Comment by paulbilnoski** [comment]
Seems to be working properly for me the past few days using the 12 Nov build. Thanks for tackling the tricky!

**Comment by fappel** [comment]
Great! Thanks for the info.
