### ISSUE TITLE
[ScrollableAdapter] SWTException upon RCP exit

### ISSUE THREAD

**Issue by jbuchberger** [fappel/xiliary#49]
When I enable `flat-scroll-bar` on `Table` and `Tree` via CSS
I frequently get SWT exceptions upon exit of RCP client.

Table:
> org.eclipse.swt.SWTException: Widget is disposed
> at org.eclipse.swt.SWT.error(SWT.java:4491)
> at org.eclipse.swt.SWT.error(SWT.java:4406)
> at org.eclipse.swt.SWT.error(SWT.java:4377)
> at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
> at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
> at org.eclipse.swt.widgets.Widget.removeListener(Widget.java:935)
> at org.eclipse.swt.dnd.DragSource.onDispose(DragSource.java:574)...

Tree:
> org.eclipse.swt.SWTException: Widget is disposed
> at org.eclipse.swt.SWT.error(SWT.java:4491)
> at org.eclipse.swt.SWT.error(SWT.java:4406)
> at org.eclipse.swt.SWT.error(SWT.java:4377)
> at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
> at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
> at org.eclipse.swt.widgets.Widget.removeListener(Widget.java:935)
> at org.eclipse.swt.dnd.DropTarget.onDispose(DropTarget.java:560)...

Debug Table:
> Table(Widget).error(int) line: 482
> Table(Widget).checkWidget() line: 354> 
> Table(Widget).removeListener(int, Listener) line: 935> 
> DragSource.onDispose() line: 574> 
> DragSource.access$1(DragSource) line: 570> 
> DragSource$2.handleEvent(Event) line: 182> 
> EventTable.sendEvent(Event) line: 84> 
> Display.sendEvent(EventTable, Event) line: 4362> 
> DragSource(Widget).sendEvent(Event) line: 1113> 
> DragSource(Widget).sendEvent(int, Event, boolean) line: 1137> 
> DragSource(Widget).sendEvent(int) line: 1118> 
> DragSource(Widget).release(boolean) line: 822> 
> DragSource(Widget).dispose() line: 460> 
> DragSource$1.handleEvent(Event) line: 167> 
> EventTable.sendEvent(Event) line: 84> 
> Display.sendEvent(EventTable, Event) line: 4362> 
> Table(Widget).sendEvent(Event) line: 1113> 
> Table(Widget).sendEvent(int, Event, boolean) line: 1137> 
> Table(Widget).sendEvent(int) line: 1118> 
> Table(Widget).release(boolean) line: 822> 
> TableAdapter(Composite).releaseChildren(boolean) line: 891> 
> TableAdapter(Table).releaseChildren(boolean) line: 3132> 
> TableAdapter(Widget).release(boolean) line: 825> 
> Composite.releaseChildren(boolean) line: 891> 
> Composite(Widget).release(boolean) line: 825> 
> ContributedPartRenderer$2(Composite).releaseChildren(boolean) line: 891> 
> ContributedPartRenderer$2(Widget).release(boolean) line: 825> 
> ContributedPartRenderer$2(Widget).dispose() line: 460> 
> ContributedPartRenderer(SWTPartRenderer).disposeWidget(MUIElement) line: 177> 
> ContributedPartRenderer.disposeWidget(MUIElement) line: 272> 
> PartRenderingEngine.safeRemoveGui(MUIElement) line: 914> 
> PartRenderingEngine.access$1(PartRenderingEngine, MUIElement) line: 842> 
> PartRenderingEngine$3.run() line: 837> 
> SafeRunner.run(ISafeRunnable) line: 42> 
> PartRenderingEngine.removeGui(MUIElement) line: 821> 

Debug Tree:
> Tree(Widget).error(int) line: 482> 
> Tree(Widget).checkWidget() line: 354> 
> Tree(Widget).removeListener(int, Listener) line: 935> 
> DropTarget.onDispose() line: 560> 
> DropTarget$2.handleEvent(Event) line: 157> 
> EventTable.sendEvent(Event) line: 84> 
> Display.sendEvent(EventTable, Event) line: 4362> 
> DropTarget(Widget).sendEvent(Event) line: 1113> 
> DropTarget(Widget).sendEvent(int, Event, boolean) line: 1137> 
> DropTarget(Widget).sendEvent(int) line: 1118> 
> DropTarget(Widget).release(boolean) line: 822> 
> DropTarget(Widget).dispose() line: 460> 
> DropTarget$1.handleEvent(Event) line: 149> 
> EventTable.sendEvent(Event) line: 84> 
> Display.sendEvent(EventTable, Event) line: 4362> 
> Tree(Widget).sendEvent(Event) line: 1113> 
> Tree(Widget).sendEvent(int, Event, boolean) line: 1137> 
> Tree(Widget).sendEvent(int) line: 1118> 
> Tree(Widget).release(boolean) line: 822> 
> TreeAdapter(Composite).releaseChildren(boolean) line: 891> 
> TreeAdapter(Tree).releaseChildren(boolean) line: 3946> 
> TreeAdapter(Widget).release(boolean) line: 825> 
> Composite.releaseChildren(boolean) line: 891> 
> Composite(Widget).release(boolean) line: 825> 
> ContributedPartRenderer$2(Composite).releaseChildren(boolean) line: 891> 
> ContributedPartRenderer$2(Widget).release(boolean) line: 825> 
> ContributedPartRenderer$2(Widget).dispose() line: 460> 
> ContributedPartRenderer(SWTPartRenderer).disposeWidget(MUIElement) line: 177> 
> ContributedPartRenderer.disposeWidget(MUIElement) line: 272> 
> PartRenderingEngine.safeRemoveGui(MUIElement) line: 914> 
> PartRenderingEngine.access$1(PartRenderingEngine, MUIElement) line: 842> 
> PartRenderingEngine$3.run() line: 837> 
> SafeRunner.run(ISafeRunnable) line: 42> 
> PartRenderingEngine.removeGui(MUIElement) line: 821>

**Comment by fappel** [comment]
Hi, thanks for traces - I will have a look at it ASAP

**Comment by jbuchberger** [comment]
* confirm fix
* TESTED using version 0.1.2 build 20151207-0938
