### ISSUE TITLE
[ScrollableAdapter] Target Platform content editor not editable

### ISSUE THREAD

**Issue by paulbilnoski** [fappel/xiliary#50]
I've run into the content editor wizard for the Target Platform configuration having a checkbox tree that is not editable, even after resizing the wizard.

![tp](https://cloud.githubusercontent.com/assets/2455397/11534190/0f751e96-98d3-11e5-91b6-9df7cfd43064.png)

I have been able to use the editor part to make these changes as a workaround instead of the transactional wizard, so it is not severe to me.

**Comment by fappel** [comment]
Thanks for reporting this. I've been pretty occupied by other things in the recent days, so I'm glad it isn't severe. But I'll look at it ASAP.
