### ISSUE TITLE
[ScrollableAdapter] SWTException upon closing dialog in RCP

### ISSUE THREAD

**Issue by jbuchberger** [fappel/xiliary#51]
*!ENTRY org.eclipse.ui 4 0 2015-12-07 14:08:26.496
!MESSAGE Unhandled event loop exception
!STACK 0*
> org.eclipse.swt.SWTException: Widget is disposed
> at org.eclipse.swt.SWT.error(SWT.java:4491)
> at org.eclipse.swt.SWT.error(SWT.java:4406)
> at org.eclipse.swt.SWT.error(SWT.java:4377)
> at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
> at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
> at org.eclipse.swt.widgets.Widget.removeListener(Widget.java:935)
> at org.eclipse.jface.window.ToolTip.deactivate(ToolTip.java:192)
> at org.eclipse.jface.window.ToolTip.toolTipHide(ToolTip.java:448)
> at org.eclipse.jface.window.ToolTip.access$1(ToolTip.java:438)
> at org.eclipse.jface.window.ToolTip$ToolTipOwnerControlListener.handleEvent(ToolTip.java:627)
> at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
> at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
> at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
> at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1137)
> at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1118)
> at org.eclipse.swt.widgets.Widget.release(Widget.java:822)
> at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:891)
> at org.eclipse.swt.widgets.Table.releaseChildren(Table.java:3132)
> at org.eclipse.swt.widgets.Widget.release(Widget.java:825)
> at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:891)
> at org.eclipse.swt.widgets.Widget.release(Widget.java:825)
> at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:891)
> at org.eclipse.swt.widgets.Canvas.releaseChildren(Canvas.java:165)
> at org.eclipse.swt.widgets.Widget.release(Widget.java:825)
> at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:891)
> at org.eclipse.swt.widgets.Widget.release(Widget.java:825)
> at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:891)
> at org.eclipse.swt.widgets.Widget.release(Widget.java:825)
> at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:891)
> at org.eclipse.swt.widgets.Widget.release(Widget.java:825)
> at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:891)
> at org.eclipse.swt.widgets.Widget.release(Widget.java:825)
> at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:891)
> at org.eclipse.swt.widgets.Widget.release(Widget.java:825)
> at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:891)
> at org.eclipse.swt.widgets.Widget.release(Widget.java:825)
> at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:891)
> at org.eclipse.swt.widgets.Widget.release(Widget.java:825)
> at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:891)
> at org.eclipse.swt.widgets.Canvas.releaseChildren(Canvas.java:165)
> at org.eclipse.swt.widgets.Decorations.releaseChildren(Decorations.java:789)
> at org.eclipse.swt.widgets.Shell.releaseChildren(Shell.java:1318)
> at org.eclipse.swt.widgets.Widget.release(Widget.java:825)
> at org.eclipse.swt.widgets.Widget.dispose(Widget.java:460)
> at org.eclipse.swt.widgets.Decorations.dispose(Decorations.java:447)
> at org.eclipse.swt.widgets.Shell.dispose(Shell.java:725)
> at org.eclipse.jface.window.Window.close(Window.java:334)
> at org.eclipse.jface.dialogs.Dialog.close(Dialog.java:990)
> at org.eclipse.jface.wizard.WizardDialog.hardClose(WizardDialog.java:862)
> at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:807)

``` Thread [main] (Suspended (breakpoint at line 4491 in SWT))```
> SWT.error(int, Throwable, String) line: 4491> 
> SWT.error(int, Throwable) line: 4406> 
> SWT.error(int) line: 4377> 
> Table(Widget).error(int) line: 482> 
> Table(Widget).checkWidget() line: 354> 
> Table(Widget).removeListener(int, Listener) line: 935> 
> ColumnViewerToolTipSupport(ToolTip).deactivate() line: 192> 
> ColumnViewerToolTipSupport(ToolTip).toolTipHide(Shell, Event) line: 448> 
> ToolTip.access$1(ToolTip, Shell, Event) line: 438> 
> ToolTip$ToolTipOwnerControlListener.handleEvent(Event) line: 627> 
> EventTable.sendEvent(Event) line: 84> 
> Display.sendEvent(EventTable, Event) line: 4362> 
> Table(Widget).sendEvent(Event) line: 1113> 
> Table(Widget).sendEvent(int, Event, boolean) line: 1137> 
> Table(Widget).sendEvent(int) line: 1118> 
> Table(Widget).release(boolean) line: 822> 
> TableAdapter(Composite).releaseChildren(boolean) line: 891> 
> TableAdapter(Table).releaseChildren(boolean) line: 3132> 
> TableAdapter(Widget).release(boolean) line: 825> 
> Composite.releaseChildren(boolean) line: 891> 
> Composite(Widget).release(boolean) line: 825> 
> Composite.releaseChildren(boolean) line: 891> 
> Composite(Widget).release(boolean) line: 825>

**Comment by fappel** [comment]
This might be related to #49 which should be fixed with commit eff00df. The reason was an insufficient disposal strategy used by the adapter mechanism. This should be better now and might also solve the problem described here. The fix is already available in the P2 repository of the CI build (development branch) at http://fappel.github.io/xiliary/development. You can redirect your target to use this repository for checking if you like.

**Comment by jbuchberger** [comment]
Yes, you're right. :-) This does not happen anymore using version 0.1.2 build 20151207-0938 from development branch.
