### ISSUE TITLE
[ScrollableAdapterContribution] Add styling to disable very thin flat-scroll-bar

### ISSUE THREAD

**Issue by jbuchberger** [fappel/xiliary#52]
The idea is to use CSS to make sure all flat scrollbars always only show the thicker thumbs.

Note, that this does not reflect my personal taste (I'd rather be able to have very-thin-only styled flat scrollbars). However, our stakeholders make integration of the flat scrollbar into our RCP client dependent on above feature.

**Comment by fappel** [comment]
I think this should be possible without too much effort, and we want to make your client happy, won't we ;-) I'm working on the ScrollableAdapter stuff this week and already started with bug fixes. Once that's done, I will go ahead with enhancement requests. As bug fixing proceeds well so far this feature will hopefully be available till the end of the week. I'll keep you posted.

**Comment by jbuchberger** [comment]
Great, thanks!
I noticed your recent fixes and just *tried* to build your current development branch in order to test it in our client. Unfortunately, I got to leave office now and due to review/retrospective/planning - I won't be able to have a closer look at it again the next couple of days.

**Comment by jbuchberger** [comment]
Thanks! Tested with 0.1.2.20151214-0727 from development repo.

Works like a charm using:
``` adapter-demeanor: fixed-width; ```

(Note that the example in the commit message is not valid CSS.)

**Comment by jbuchberger** [comment]
While testing, I noticed there are new dependencies in the __theme MANIFEST__ ...
one of them ```org.eclipse.core.runtime;bundle-version="[3.11.1,4.0.0)"```
requires updating that plugin in the target platform in case one cannot update yet to __Mars.1__

**Comment by fappel** [comment]
Thanks for noting that one. I will reduce the lower boundaries of the new dependencies.
