### ISSUE TITLE
Commit & Compare views don't update on showing

### ISSUE THREAD

**Issue by i82orbom** [fappel/xiliary#64]
When committing or comparing files using the eclipse Team tools, the tables don't update on opening.

A window resize, or modifying the position of the split pane is required to cause the window to repaint and show the contents.

Before:
![image](https://cloud.githubusercontent.com/assets/1162226/14168078/09606d98-f720-11e5-8438-bba930253817.png)

After resizing the window or moving one of the split panes using the gripper. (I removed some content from the picture). But basically the content that it supposed to appear in the view, after moving or resizing is there.

Probably the window is not repainting correctly.

![image](https://cloud.githubusercontent.com/assets/1162226/14168100/36059f08-f720-11e5-80af-1a77bed19a76.png)

I am using Eclipse Mars S2 on Windows 8.1.

**Comment by fappel** [comment]
Thanks for reporting this issue. I will have a look ASAP. However, since I'm on holidays right now it might take a while

**Comment by psylock** [comment]
Hi,

thanks for the quick feedback. Not hurry at all, it's an issue indeed but can be solved by resizing the window as I've commented.

**Comment by fappel** [comment]
The fix is available for check out within the P2 repository of the latest CI Build at http://fappel.github.io/xiliary/development/. It will be released with the next master build if there aren't any objections.
