### ISSUE TITLE
[Clean Sheet] Broken fonts after install (codepage?)

### ISSUE THREAD

**Issue by twh270** [fappel/xiliary#71]
I have a clean install of STS 3.7.3. After installing Clean Sheet my fonts are a bit broken:

![image](https://cloud.githubusercontent.com/assets/2341371/16360156/0e0c5ac4-3b17-11e6-9212-59e06a280ec3.png)

The theme looks very nice, but this issue makes it a non-starter. I'll be glad to help fix/debug.

EDIT: I forgot that I had overridden the default text font to use SourceCodePro Semibold. If I revert to SourceCodePro Regular and remove all lines containing "Semibold" from  `org.eclipse.ui.workbench.prefs` all is good.

So, it appears the real defect here is Clean Sheet doesn't like it when the editor font is changed.

**Comment by fappel** [comment]
Thanks for reporting this issue. It didn't imagine that changing the font style could cause any trouble. But you never stop learning. I will have a look at it ASAP and see if I can reproduce it. Thanks a lot for the hands-on offer. Help is always appreciated. Do you have any additional information like your OS, suspicious error log entries and the like?

**Comment by twh270** [comment]
My OS is Windows 7, and no, I don't see anything else suspicious. 

I found out the Medium weight font is working as expected. Strange behavior.

**Comment by twh270** [comment]
I discovered that Clean Sheet ships with the SourceCodePro fonts. I already have these fonts installed in Windows, but my font files are a different datestamp/size (yours are no doubt newer, as I installed when SourceCodePro was first released).

After uninstalling my SourceCodePro fonts from Windows and installing the ones from the plugin, everything is happy again. It appears the problem is caused by the installed system fonts differing from the plugin font files. Bit of a corner case...!

I'm closing this bug as I have a working environment now and don't think this is a real defect in Clean Sheet.

**Comment by fappel** [comment]
Great that it works for you know. Didn't think about that corner case. But in my opinion, it is something Clean Sheet should handle as it is a valid system configuration. One might use Source Code Pro in other programs as well. Then uninstallation of the font isn't an option. Hence, I've opened a follow-up issue #72 that should tackle this problem. Thanks again for reporting this, it will help to make Clean Sheet more robust.
