### ISSUE TITLE
[Clean Sheet] Black background in current line when debug

### ISSUE THREAD

**Issue by RogelioHIT** [fappel/xiliary#74]
I have a problem when debugging, because the background of the line that is currently in debug, is black and the color is also black, so it's very difficult to read, i attached a screenshot of the problem.

![captura de pantalla 2016-08-18 a las 8 59 57 a m](https://cloud.githubusercontent.com/assets/8886223/17776464/5aa02e9e-6522-11e6-8dbb-5d7811d7e1ae.png)

I'm working on a mac, el capitan and the version of eclipse is mars.

I wonder if it's only my problem, but i don't know, i have set clean sheet many times and this happens.

thanks guys

PD. also the brackets are white in the image but in that case i can change the color of them.

**Comment by fappel** [comment]
Thanks for reporting this problem. We'll have a look at it ASAP.

**Comment by hstaudacher** [comment]
I can't confirm this issue. See screenshot

<img width="408" alt="screen shot 2016-08-23 at 09 29 30" src="https://cloud.githubusercontent.com/assets/289648/17883661/2827b57c-6914-11e6-87f8-f9bb87cac5dd.png">

**Comment by fappel** [comment]
Hm, not sure what to make of this at them moment. Maybe a list of the installed plug-ins or the eclipse-download package might provide a hint...

**Comment by RogelioHIT** [comment]
Hello again, yes i do have eclipse color theme installed, maybe thats the reason, i will uninstall that plugin and see if that helps, thanks guys

**Comment by fappel** [comment]
No Problem at all! I'm glad that it works for you :-)
