### ISSUE TITLE
[CleanSheet] Not updated code line numbers during scrollbar mouse move

### ISSUE THREAD

**Issue by dex-ds** [fappel/xiliary#75]
Hi Frank, during a scrollbar moving with mouse (left mouse button pressed on bar and moving up or down) the code line numbers are not updated. 
Greetings,
Daniel

**Comment by dex-ds** [comment]
my workaround at this time disable this in clean-sheet-win.css
```
StyledText {
  flat-scroll-bar: false;
```

**Comment by fappel** [comment]
Hi Daniel,

thanks for reporting this issue. I'm able to reproduce the behavior and I'll have a look at it ASAP. However, this might take a while as I'm pretty busy at the moment.

Greetings
Frank
