### ISSUE TITLE
[Clean Sheet] Can't change text editor font

### ISSUE THREAD

**Issue by javahacks** [fappel/xiliary#93]
Many thanks for your  polished theme.  However I can't change the default text editor font under General->Appearance->Colors and Fonts. The text editor always uses source code pro with a fixed font size. I personally prefer Jetbrains Mono especially its font ligartures.

**Comment by fappel** [comment]
Thanks for being interested in Clean Sheet. Sorry, that you ran into issues. However, to understand the problem correctly: I just tried to reproduce your problem and changed font-family settings for both, text and java-editor - each time the change of settings where correctly applied. So let me ask which OS, Eclipse, and Java Version you are using and if you can find any issue related entries with stacktraces in the log of the Error View. Thank you very much for your feedback!

**Comment by javahacks** [comment]
I use Windows 10, Java version ist Adopt OpenJDK 13, Eclipse Version 
Eclipse DSL Tools Version: 2020-03 (4.15.0) Build id: 20200313-1211
Sorry, I haven't found any useful stacktrace or error log information
In the image below you see that font setting is correctly applied to XML Editor on the left but didn't change for Java text editor on the right.
![image](https://user-images.githubusercontent.com/910776/80679629-8d29cb80-8abd-11ea-8248-b179f808d8a6.png)

**Comment by fappel** [comment]
<img width="626" alt="Screenshot 2020-04-30 at 20 21 00" src="https://user-images.githubusercontent.com/776277/80745196-36a1a900-8b20-11ea-9cb3-4f243770513f.png">
If you scroll down a little bit there is another possibility to set the font for the java editor. This should do the trick if I'm not mistaken

**Comment by javahacks** [comment]
Yes that solves the problem for Java editors. I didn't see that your Stylesheet overrides the default font for most text editors and it's really tedious to reset them all. Maybe you should just change the default font.

**Comment by fappel** [comment]
I'm glad that the problem could be solved. I consider your suggestion regarding simplification of text editor font settings.
